version: '3.3'



services:
    app:
        container_name: farm_nginx
        build:
            context: ./dockerfiles
            dockerfile: nginx.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html:delegated
        depends_on:
            - php
            - redis
        networks:
            - dom_network

    php:
        container_name: farm_php
        build:
            context: ./dockerfiles
            dockerfile: php.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www/html:delegated
        networks:
            - dom_network

    redis:
        image: redis:alpine
        container_name: farm_redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - dom_network

networks:
    dom_network:
